CarShop/CarShop/Controllers/CarController.cs
using CarShop.Models;
using CarShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CarShop.Controllers
{
    public class CarController : Controller
    {
      private readonly ICarRepository _carRepository;
      private readonly ICompanyRepository _companyRepository;

     
     public CarController(ICarRepository carRepository, ICompanyRepository companyRepository)
        {
            _carRepository = carRepository;
            _companyRepository = companyRepository;
        }

        public IActionResult List()
        {
            CarListViewModel carListViewModel = new CarListViewModel(_carRepository.GetAllCars, "Cars");
            return View(carListViewModel);
        }

        public IActionResult Details(int id) {
        
        var car = _carRepository.GetCarById(id);
            if (car == null) { return NotFound(); }
            return View(car);
        }

        public IActionResult Search() 
        {
            return View();
        }
    }
}

CarShop/CarShop/Controllers/OrderController.cs
using CarShop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarShop.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly IShoppingCart _shoppingCart;

        public OrderController(IOrderRepository orderRepository, IShoppingCart shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            // Ensure ShoppingCartItems is initialized
            var items = _shoppingCart.GetShoppingCartItems();

            // Check if the cart is empty
            if (items.Count == 0)
            {
                ModelState.AddModelError(string.Empty, "Add a car first!");
            }

            //if (ModelState.IsValid)
            //{
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();
                return RedirectToAction("CheckoutComplete");
           // }

           // return View(order);
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = "Thanks!";
            return View();
        }
    }
}

CarShop/CarShop/Views/Shared/_CarCard.cshtml
@model Car

<div class="col">
    <div class="card car-card">
        <img src="@Url.Content("~/images/" + @Model.ImageURL)" class="card-img-top" alt="@Model.Name">







        <div class="card-body car-button">
            <h4 class="d-grid">
            </h4>
            <h4 class="d-grid">
                <a class="btn btn-secondary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShoppingCart"
                   asp-route-carId="@Model.CarId"> + Add to cart</a>
            </h4>

            <div class="d-flex justify-content-between mt-2">
                <h2 class="text-start">
                    <a class="car-link" asp-controller="Car" asp-action="Details" asp-route-id="@Model.CarId">@Model.Name</a>
                </h2>
                <h5 class="text-nowrap">
                    @Model.Price.ToString("c")
                </h5>
            </div>
        </div>
    </div>
</div>

CarShop/CarShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
   
        <title>Cars Shop</title>
    <link href='https://fonts.googleapis.com/css?family=Work+Sans' rel='stylesheet' type='text/css'>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/css/site.css" rel="stylesheet" />
    </head>

<body>
    <div class="container">
        <header class="header">
            <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-primary" aria-label="Car Shop navigation header">
                <div class="container-xl">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                        <img src="@Url.Content("~/images/CarShopLogo.jpg")" width="151" height="47" class="d-inline-block align-top mb-2 mt-1" alt="CarShop_logo">
                    </a>
                    <div class="header-links">
                        <div class="button-group">
                            <!-- Wrap buttons in a div for stacking -->
                            <a class="list-all-cars" asp-controller="Car" asp-action="List">
                                List All Cars
                            </a>
                            <a class="btn btn-primary" asp-controller="Order" asp-action="Checkout">
                                Checkout Now!
                            </a>
                        </div>
                        <ul class="navbar-nav mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Car" asp-action="Search">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                                    </svg>
                                </a>
                            </li>
                        </ul>
                        <vc:vc:shopping-cart-summary></vc:vc:shopping-cart-summary>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        </header>



        @RenderBody()
        @RenderSection("Scripts",required:false)
    </div>
</body>
</html>